# Generated by Django 4.0.4 on 2022-04-18 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hometypes', '0001_initial'),
        ('balcons', '0001_initial'),
        ('bathrooms', '0001_initial'),
        ('metro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numbers_flat', models.IntegerField()),
                ('price', models.IntegerField()),
                ('square_meters', models.IntegerField()),
                ('address', models.CharField(max_length=255)),
                ('balcon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='balcons.balcon')),
                ('bath_room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bathrooms.bathroom')),
                ('metro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='metro.metro')),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hometypes.hometypes')),
            ],
        ),
    ]
