# Generated by Django 4.0.4 on 2022-04-18 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0001_initial'),
        ('mainbase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainbase',
            name='holders',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='owners.owner'),
        ),
    ]
